[package]
name = "fangraphs-learn-to-code"
version = "0.1.0"
authors = ["Eli Ben-Porat <fangraphs-learn@ben-porat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "0.9"
